ctid:
  image: quintana/ctid
  ports:
   - "5003:5003"
   - "5004:5004"
   - "9495:9495"
  links:
   - db
   - bus
   - dird
   - asterisk
   - provd
   - agentd
  volumes:
   - ctid:/etc/xivo-ctid/conf.d
dird:
  image: quintana/dird
  ports:
   - "9489:9489"
  links:
   - confd
  volumes:
   - dird/conf.d:/etc/xivo-dird/conf.d
   - dird/sources.d:/etc/xivo-dird/sources.d
   - dird/csv:/tmp/csv
confd:
  image: quintana/confd
  ports:
   - "9486:9486"
  links:
   - db
   - bus
   - provd
  volumes:
   - confd:/etc/xivo-confd/
agid:
  image: quintana/agid
  ports:
   - "4573:4573"
  links:
   - db
  volumes:
   - agid:/etc/xivo-agid/conf.d
agentd:
  image: quintana/agentd
  ports:
   - "9486:9486"
  volumes:
   - agentd:/etc/xivo-agentd/conf.d
confgend:
  image: quintana/confgend
  ports:
   - "8669:8669"
  links:
   - db
  volumes:
   - confgend:/etc/xivo/
sysconfd:
  image: quintana/sysconfd
  ports:
   - "8668:8668"
  links:
   - bus
  volumes:
   - sysconfd:/etc/xivo/sysconfd
provd:
  image: quintana/provd
  ports:
   - "8667:8667"
   - "8666:8666"
   - "69:69/udp"
  volumes:
   - provd:/etc/xivo/provd/
dxtora:
  image: quintana/dxtora
  volumes:
   - dxtora:/etc/xivo-dxtora/
calllogd:
  image: quintana/call-logd
  volumes:
   - call-logd:/etc/xivo-call-logs/conf.d
amid:
  image: quintana/amid
  links:
   - asterisk
   - bus
  volumes:
   - amid:/etc/xivo-amid/conf.d
webi:
  image: quintana/webi
  ports:
   - "80:80"
   - "443:443"
  links:
   - db
   - sysconfd
   - confd
   - provd
  volumes:
   - webi/nginx:/etc/nginx/sites-enabled
   - webi/ssl:/etc/nginx/ssl
   - webi/etc:/etc/xivo/web-interface
asterisk:
  image: quintana/asterisk11
  ports:
   - "5060:5060/udp"
   - "2000:2000"
  links:
   - confgend
  expose:
   - "5038"
  volumes:
   - odbc:/etc/odbc/
   - confgend-client:/etc/xivo-confgend-client/
db:
  image: postgres
  expose:
   - "5432"
bus:
  image: dockerfile/rabbitmq
  expose:
   - "5672"
