# Change the log level to debug level.
debug: True

# Change the log level. Values are: critical, error, warning, info, debug.
log_level: info

# Log file.
log_filename: /var/log/xivo-confd.log

# PID file.
pid_filename: /var/run/xivo-confd/xivo-confd.pid

# REST API server
rest_api:

    # Listening address
    listen: 0.0.0.0

    # Listening port
    port: 9486

# Event bus (AMQP) connection informations
bus:
    username: xivo
    password: xivo
    host: 192.168.113.99
    port: 5672
    exchange_name: xivo
    exchange_type: topic
    exchange_durable: True

db_uri: postgresql://asterisk:proformatique@192.168.113.99/asterisk

# Extra resources to load
#extra_plugins:
#   - resource_name
