source_config_dir: /etc/xivo-dird/sources.d
rest_api:
       listen: 127.0.0.1
       port: 9489

enabled_plugins:
    backends:
        - sample
    services:
        - lookup
    views:
        - default_json
        - headers_view

views:
    displays:
        default_display:
            -
                title: Firstname
                default: Unknown
                field: firstname
            -
                title: Lastname
                default: Unknown
                field: lastname
            -
                title: Description
                default:
                field: description
    profile_to_display:
        default: default_display

services:
    lookup:
        default:
            sources:
                - my_sample
            timeout: 0.5
