auth:
    host: 192.168.32.248

consul:
    host: 192.168.32.248

enabled_plugins:
    backends:
        - xivo
        - ldap
        - personal
    services:
        - lookup
        - favorites
        - personal
    views:
        - default_json
        - headers_view
        - personal_view

views:
    displays:
        default_display:
            -
                title: Prénom
                default: Unknown
                field: firstname
                type: name
            -
                title: Nom
                default: Unknown
                field: lastname
                type: name
            -
                title: Numéro
                default:
                field: exten
                type: number
            -
                title: Mobile
                default:
                field: mobile_phone_number
                type: mobile
            -
                title: Agent
                default:
                field: agent
                type: agent
            -
                title: Favoris
                field: favorite
                type: favorite
            -
                title: Personnel
                field: personal
                type: personal

    profile_to_display:
        default: default_display
        intern: default_display
        default_ac: default_display

services:
    lookup:
        default:
            sources:
                - xivo_quebec
                - xivo_limonest
                - xivo_suresnes
                - xivo_rennes
                - xivo_toulouse
                - my_ldap
            timeout: 0.5
        default_ac:
            sources:
                - xivo_quebec
                - xivo_limonest
                - xivo_suresnes
                - xivo_rennes
                - xivo_toulouse
                - my_ldap
            timeout: 0.5
        intern:
            sources:
                - xivo_quebec
                - xivo_limonest
                - xivo_suresnes
                - xivo_rennes
                - xivo_toulouse
                - my_ldap
            timeout: 0.5
    favorites:
        default:
            sources:
                - xivo_quebec
                - xivo_limonest
                - xivo_suresnes
                - xivo_rennes
                - xivo_toulouse
                - my_ldap
                - personal
            timeout: 0.5
        default_ac:
            sources:
                - xivo_quebec
                - xivo_limonest
                - xivo_suresnes
                - xivo_rennes
                - xivo_toulouse
                - my_ldap
                - personal
            timeout: 0.5
        intern:
            sources:
                - xivo_quebec
                - xivo_sylvain
                - xivo_limonest
                - xivo_suresnes
                - xivo_rennes
                - xivo_toulouse
                - my_ldap
                - personal
            timeout: 0.5
