enabled_plugins:
    backends:
        - xivo
        - csv
        - ldap
    services:
        - lookup
    views:
        - default_json
        - headers_view

views:
    displays:
        default_display:
            -
                title: Firstname
                default: Unknown
                field: firstname
                type: name
            -
                title: Lastname
                default: Unknown
                field: lastname
                type: name
            -
                title: Number
                default:
                field: exten
                type: number
            -
                title: Description
                default:
                field: description
            -
                title: Agent
                default:
                field: agent
                type: agent
    profile_to_display:
        default: default_display
        internal-sylvain: default_display
        intern: default_display
        default_ac: default_display

services:
    lookup:
        default:
            sources:
                - xivo_quebec
                - xivo_sylvain
                - xivo_sylvain_dev
                - xivo_limonest
                - xivo_suresnes
                - xivo_rennes
                - xivo_toulouse
                - my_ldap
            timeout: 0.5
        default_ac:
            sources:
                - xivo_quebec
                - xivo_sylvain
                - xivo_limonest
                - xivo_suresnes
                - xivo_rennes
                - xivo_toulouse
            timeout: 0.5
        internal-sylvain:
            sources:
                - xivo_sylvain
                - my_csv
        intern:
            sources:
                - xivo_quebec
                - xivo_sylvain
                - xivo_limonest
                - xivo_suresnes
                - xivo_rennes
                - xivo_toulouse
                - my_csv
            timeout: 0.5
